### ISSUE TITLE
doorOpensHandler() hard-coded check for "Night" mode is limiting

### ISSUE THREAD

**Issue by johnruemker** [arnbme/SHMDelay#1]
The True Night Mode setting depends on there being a mode called exactly "Night", which may not be ideal for everyone - like me.

SHM only has 3 armed states: disarmed, armed (home), and armed (away).  As such, I don't have a strong need to set up different day/night modes when we're home and armed - instead I just operate on whether I'm active (disarmed) or staying put (stay).  

With this mode set, I found True Night Mode didn't work.  I had to change my 'Stay' mode to 'Night' to get it to work, and that naming is a little awkward for how I use it (which isn't exclusive to night time).

Hypothetically someone could reasonably want to have their system armed for instant-intrusion alarms during the day while their daytime-focused routines and rules and such are in play.  This current setup prevents that.

It'd be great if this could be modified to allow selecting which mode(s) the no-delay situation applies to.

P.S.  Awesome app!  You rock!

**Comment by arnbme** [comment]
John
Sorry for the _very slow_ response to your suggestion, I use github only with my SmartThing source. Never expected a message here, only on the ST Community Forum.

However, I understand some ST users may rename or use the modes in a non default manner, and this could negatively impact proper functioning of the app.

I will take a look at the code and see what can be done to mitigate this issue.

Kindly post any future comments on the ST Community Forum
